# Generated by Django 4.2.4 on 2023-08-21 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='upload_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='employee_data/static/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FilePathField(path='employee_data/images'),
        ),
    ]
