# Generated by Django 4.2.4 on 2023-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_employee_upload_image_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='upload_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
