# Generated by Django 4.2.4 on 2023-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0005_alter_employee_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FilePathField(path='/uploads/uploads'),
        ),
    ]
