# Generated by Django 4.2.4 on 2023-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FilePathField(path='employee_data/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='upload_image',
            field=models.ImageField(upload_to='./'),
        ),
    ]
