# Generated by Django 4.2.4 on 2023-08-29 11:10

from django.db import migrations, models
import employee_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0007_alter_employee_image_alter_employee_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='upload_image',
            field=models.ImageField(blank=True, upload_to=employee_data.models.get_image_path),
        ),
    ]
